-- ============================================================
-- LIVELINE — 05_posts.sql
-- Short-form moment posts (≤5 second video / image)
-- ============================================================

CREATE TABLE public.posts (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

    media_url       TEXT NOT NULL,
    media_type      TEXT NOT NULL CHECK (media_type IN ('image', 'video')),

    -- Thumbnail for video posts (generated by FFmpeg)
    thumbnail_url   TEXT,

    -- Processed media dimensions (for masonry layout; nullable for legacy rows)
    media_width     INT,
    media_height    INT,

    -- Duration in seconds — must be ≤ 5 for video
    duration_sec    NUMERIC(4,2)
                        CHECK (
                            media_type = 'image'
                            OR (media_type = 'video' AND duration_sec IS NOT NULL AND duration_sec <= 5)
                        ),

    caption         TEXT CHECK (length(caption) <= 300),

    -- Optional attached music track
    music_id        UUID REFERENCES public.music_activity(id) ON DELETE SET NULL,

    -- Audience visibility
    visibility      TEXT NOT NULL DEFAULT 'friends'
                        CHECK (visibility IN ('public', 'friends', 'private')),

    -- 24-hour lifecycle or null for permanent
    expires_at      TIMESTAMPTZ,

    -- Soft delete
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,

    -- Engagement counters (denormalised for fast reads)
    like_count      INT NOT NULL DEFAULT 0,
    view_count      INT NOT NULL DEFAULT 0,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_posts_user_id     ON public.posts (user_id);
CREATE INDEX idx_posts_created_at  ON public.posts (created_at DESC);
CREATE INDEX idx_posts_expires_at  ON public.posts (expires_at)
    WHERE expires_at IS NOT NULL;
CREATE INDEX idx_posts_visibility  ON public.posts (visibility);
CREATE INDEX idx_posts_active      ON public.posts (user_id, created_at DESC)
    WHERE is_deleted = FALSE;

CREATE TRIGGER set_posts_updated_at
    BEFORE UPDATE ON public.posts
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ----------------------------------------------------------------
-- Post Likes
-- ----------------------------------------------------------------
CREATE TABLE public.post_likes (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id     UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (post_id, user_id)
);

CREATE INDEX idx_post_likes_post_id ON public.post_likes (post_id);
CREATE INDEX idx_post_likes_user_id ON public.post_likes (user_id);

-- Keep like_count in sync
CREATE OR REPLACE FUNCTION sync_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.posts SET like_count = like_count + 1 WHERE id = NEW.post_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE public.posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.post_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sync_post_like_count
    AFTER INSERT OR DELETE ON public.post_likes
    FOR EACH ROW EXECUTE FUNCTION sync_post_like_count();

-- ----------------------------------------------------------------
-- Post Views
-- ----------------------------------------------------------------
CREATE TABLE public.post_views (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id     UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    viewer_id   UUID REFERENCES public.users(id) ON DELETE SET NULL,  -- null = anonymous
    viewed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_post_views_post_id   ON public.post_views (post_id);
CREATE INDEX idx_post_views_viewer_id ON public.post_views (viewer_id);

-- Keep view_count in sync
CREATE OR REPLACE FUNCTION sync_post_view_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.posts SET view_count = view_count + 1 WHERE id = NEW.post_id;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sync_post_view_count
    AFTER INSERT ON public.post_views
    FOR EACH ROW EXECUTE FUNCTION sync_post_view_count();

-- ----------------------------------------------------------------
-- Post Comments (optional but complete)
-- ----------------------------------------------------------------
CREATE TABLE public.post_comments (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id     UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    body        TEXT NOT NULL CHECK (length(body) >= 1 AND length(body) <= 500),
    is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_post_comments_post_id ON public.post_comments (post_id, created_at ASC);
CREATE INDEX idx_post_comments_user_id ON public.post_comments (user_id);

CREATE TRIGGER set_post_comments_updated_at
    BEFORE UPDATE ON public.post_comments
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
