-- ============================================================
-- LIVELINE — 12_storage.sql
-- Supabase Storage bucket definitions + access policies
-- ============================================================

-- ----------------------------------------------------------------
-- Create Buckets
-- ----------------------------------------------------------------

-- Profile pictures
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'avatars',
    'avatars',
    TRUE,
    5242880,  -- 5 MB
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- Banner images
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'banners',
    'banners',
    TRUE,
    10485760,  -- 10 MB
    ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Post media (images + 5-second videos)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'posts',
    'posts',
    FALSE,
    52428800,  -- 50 MB (raw video before FFmpeg compression)
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif',
          'video/mp4', 'video/quicktime', 'video/webm']
)
ON CONFLICT (id) DO NOTHING;

-- Processed media output from FFmpeg pipeline
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'posts-processed',
    'posts-processed',
    TRUE,
    20971520,  -- 20 MB
    ARRAY['image/jpeg', 'image/webp', 'video/mp4']
)
ON CONFLICT (id) DO NOTHING;

-- Post thumbnails (generated by FFmpeg)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'thumbnails',
    'thumbnails',
    TRUE,
    1048576,  -- 1 MB
    ARRAY['image/jpeg', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------
-- Storage RLS Policies
-- ----------------------------------------------------------------

-- AVATARS: public read, owner write
CREATE POLICY "avatars: public read"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'avatars');

CREATE POLICY "avatars: owner upload"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'avatars'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

CREATE POLICY "avatars: owner delete"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'avatars'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- BANNERS: same pattern
CREATE POLICY "banners: public read"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'banners');

CREATE POLICY "banners: owner upload"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'banners'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

CREATE POLICY "banners: owner delete"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'banners'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- POSTS (raw): owner upload, service role processes
CREATE POLICY "posts: owner upload"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'posts'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

CREATE POLICY "posts: owner read own"
    ON storage.objects FOR SELECT
    USING (
        bucket_id = 'posts'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- POSTS-PROCESSED: public read (CDN-served), service role write only
CREATE POLICY "posts-processed: public read"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'posts-processed');

-- THUMBNAILS: public read
CREATE POLICY "thumbnails: public read"
    ON storage.objects FOR SELECT
    USING (bucket_id = 'thumbnails');
